---
  - name: adding docker repo's gpg key
    rpm_key: state=present key=https://yum.dockerproject.org/gpg

  - name: copying docker repo config to /etc/yum.repos.d
    copy: src=docker.repo dest=/etc/yum.repos.d

  - name: installing docker-engine
    yum: name={{ item }} state=present
    with_items:
      - docker-engine
      - docker-python

  - name: enabling and starting docker.service
    service: name=docker state=started enabled=yes

  - name: creating nginx directory for storing vhost revproxy configurations
    file: path=/etc/nginx/conf.d state=directory mode=0770

  - name: copying vhost config file
    template: src=vhost.conf.j2 dest=/etc/nginx/conf.d/vhost.conf

  - name: creating nginx container
    docker:
      name: nginx
      hostname: nginx
      image: "{{ docker_image }}"
      state: reloaded
      memory_limit: 64MB
      volumes:
        - /etc/nginx/conf.d:/etc/nginx/conf.d:ro
      ports:
        - 80:80
      restart_policy: always
